---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-catchall-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-catchall-server
  template:
    metadata:
      labels:
        app: go-catchall-server
    spec:
      containers:
        - name: go-catchall-server
          image: hecomp/catchalldomainname:latest
          ports:
            - containerPort: 3000