---
apiVersion: v1
kind: Service
metadata:
  name: go-catchall-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: go-catchall-server
